window:
  padding:
    x: 10
    y: 10

  dynamic_padding: false
  opacity: 0.85
  title: Terminal
  dynamic_title: false

font:
  normal:
    family: fira code
  
draw_bold_text_with_bright_colors: true

cursor:
  style:
    shape: Beam
    blinking: On

live_config_reload: true

colors: 
    transparent_background_colors: true
